# Generated by Django 3.1.7 on 2021-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.CharField(default='image', max_length=100),
            preserve_default=False,
        ),
    ]
